// Code generated by github.com/mikekonan/go-countries@generator. DO NOT EDIT.
package country

var (
	Afghanistan = Country{
		name:   NameAfghanistan,
		alpha2: Alpha2AF,
		alpha3: Alpha3AFG,
	}
	Albania = Country{
		name:   NameAlbania,
		alpha2: Alpha2AL,
		alpha3: Alpha3ALB,
	}
	Algeria = Country{
		name:   NameAlgeria,
		alpha2: Alpha2DZ,
		alpha3: Alpha3DZA,
	}
	AmericanSamoa = Country{
		name:   NameAmericanSamoa,
		alpha2: Alpha2AS,
		alpha3: Alpha3ASM,
	}
	Andorra = Country{
		name:   NameAndorra,
		alpha2: Alpha2AD,
		alpha3: Alpha3AND,
	}
	Angola = Country{
		name:   NameAngola,
		alpha2: Alpha2AO,
		alpha3: Alpha3AGO,
	}
	Anguilla = Country{
		name:   NameAnguilla,
		alpha2: Alpha2AI,
		alpha3: Alpha3AIA,
	}
	Antarctica = Country{
		name:   NameAntarctica,
		alpha2: Alpha2AQ,
		alpha3: Alpha3ATA,
	}
	AntiguaAndBarbuda = Country{
		name:   NameAntiguaAndBarbuda,
		alpha2: Alpha2AG,
		alpha3: Alpha3ATG,
	}
	Argentina = Country{
		name:   NameArgentina,
		alpha2: Alpha2AR,
		alpha3: Alpha3ARG,
	}
	Armenia = Country{
		name:   NameArmenia,
		alpha2: Alpha2AM,
		alpha3: Alpha3ARM,
	}
	Aruba = Country{
		name:   NameAruba,
		alpha2: Alpha2AW,
		alpha3: Alpha3ABW,
	}
	Australia = Country{
		name:   NameAustralia,
		alpha2: Alpha2AU,
		alpha3: Alpha3AUS,
	}
	Austria = Country{
		name:   NameAustria,
		alpha2: Alpha2AT,
		alpha3: Alpha3AUT,
	}
	Azerbaijan = Country{
		name:   NameAzerbaijan,
		alpha2: Alpha2AZ,
		alpha3: Alpha3AZE,
	}
	Bahamas = Country{
		name:   NameBahamas,
		alpha2: Alpha2BS,
		alpha3: Alpha3BHS,
	}
	Bahrain = Country{
		name:   NameBahrain,
		alpha2: Alpha2BH,
		alpha3: Alpha3BHR,
	}
	Bangladesh = Country{
		name:   NameBangladesh,
		alpha2: Alpha2BD,
		alpha3: Alpha3BGD,
	}
	Barbados = Country{
		name:   NameBarbados,
		alpha2: Alpha2BB,
		alpha3: Alpha3BRB,
	}
	Belarus = Country{
		name:   NameBelarus,
		alpha2: Alpha2BY,
		alpha3: Alpha3BLR,
	}
	Belgium = Country{
		name:   NameBelgium,
		alpha2: Alpha2BE,
		alpha3: Alpha3BEL,
	}
	Belize = Country{
		name:   NameBelize,
		alpha2: Alpha2BZ,
		alpha3: Alpha3BLZ,
	}
	Benin = Country{
		name:   NameBenin,
		alpha2: Alpha2BJ,
		alpha3: Alpha3BEN,
	}
	Bermuda = Country{
		name:   NameBermuda,
		alpha2: Alpha2BM,
		alpha3: Alpha3BMU,
	}
	Bhutan = Country{
		name:   NameBhutan,
		alpha2: Alpha2BT,
		alpha3: Alpha3BTN,
	}
	Bolivia = Country{
		name:   NameBolivia,
		alpha2: Alpha2BO,
		alpha3: Alpha3BOL,
	}
	BonaireSintEustatiusAndSaba = Country{
		name:   NameBonaireSintEustatiusAndSaba,
		alpha2: Alpha2BQ,
		alpha3: Alpha3BES,
	}
	BosniaAndHerzegovina = Country{
		name:   NameBosniaAndHerzegovina,
		alpha2: Alpha2BA,
		alpha3: Alpha3BIH,
	}
	Botswana = Country{
		name:   NameBotswana,
		alpha2: Alpha2BW,
		alpha3: Alpha3BWA,
	}
	BouvetIsland = Country{
		name:   NameBouvetIsland,
		alpha2: Alpha2BV,
		alpha3: Alpha3BVT,
	}
	Brazil = Country{
		name:   NameBrazil,
		alpha2: Alpha2BR,
		alpha3: Alpha3BRA,
	}
	BritishIndianOceanTerritory = Country{
		name:   NameBritishIndianOceanTerritory,
		alpha2: Alpha2IO,
		alpha3: Alpha3IOT,
	}
	BruneiDarussalam = Country{
		name:   NameBruneiDarussalam,
		alpha2: Alpha2BN,
		alpha3: Alpha3BRN,
	}
	Bulgaria = Country{
		name:   NameBulgaria,
		alpha2: Alpha2BG,
		alpha3: Alpha3BGR,
	}
	BurkinaFaso = Country{
		name:   NameBurkinaFaso,
		alpha2: Alpha2BF,
		alpha3: Alpha3BFA,
	}
	Burundi = Country{
		name:   NameBurundi,
		alpha2: Alpha2BI,
		alpha3: Alpha3BDI,
	}
	CaboVerde = Country{
		name:   NameCaboVerde,
		alpha2: Alpha2CV,
		alpha3: Alpha3CPV,
	}
	Cambodia = Country{
		name:   NameCambodia,
		alpha2: Alpha2KH,
		alpha3: Alpha3KHM,
	}
	Cameroon = Country{
		name:   NameCameroon,
		alpha2: Alpha2CM,
		alpha3: Alpha3CMR,
	}
	Canada = Country{
		name:   NameCanada,
		alpha2: Alpha2CA,
		alpha3: Alpha3CAN,
	}
	CaymanIslands = Country{
		name:   NameCaymanIslands,
		alpha2: Alpha2KY,
		alpha3: Alpha3CYM,
	}
	CentralAfricanRepublic = Country{
		name:   NameCentralAfricanRepublic,
		alpha2: Alpha2CF,
		alpha3: Alpha3CAF,
	}
	Chad = Country{
		name:   NameChad,
		alpha2: Alpha2TD,
		alpha3: Alpha3TCD,
	}
	Chile = Country{
		name:   NameChile,
		alpha2: Alpha2CL,
		alpha3: Alpha3CHL,
	}
	China = Country{
		name:   NameChina,
		alpha2: Alpha2CN,
		alpha3: Alpha3CHN,
	}
	ChristmasIsland = Country{
		name:   NameChristmasIsland,
		alpha2: Alpha2CX,
		alpha3: Alpha3CXR,
	}
	Cocos = Country{
		name:   NameCocos,
		alpha2: Alpha2CC,
		alpha3: Alpha3CCK,
	}
	Colombia = Country{
		name:   NameColombia,
		alpha2: Alpha2CO,
		alpha3: Alpha3COL,
	}
	Comoros = Country{
		name:   NameComoros,
		alpha2: Alpha2KM,
		alpha3: Alpha3COM,
	}
	DemocraticRepublicOfTheCongo = Country{
		name:   NameDemocraticRepublicOfTheCongo,
		alpha2: Alpha2CD,
		alpha3: Alpha3COD,
	}
	Congo = Country{
		name:   NameCongo,
		alpha2: Alpha2CG,
		alpha3: Alpha3COG,
	}
	CookIslands = Country{
		name:   NameCookIslands,
		alpha2: Alpha2CK,
		alpha3: Alpha3COK,
	}
	CostaRica = Country{
		name:   NameCostaRica,
		alpha2: Alpha2CR,
		alpha3: Alpha3CRI,
	}
	Croatia = Country{
		name:   NameCroatia,
		alpha2: Alpha2HR,
		alpha3: Alpha3HRV,
	}
	Cuba = Country{
		name:   NameCuba,
		alpha2: Alpha2CU,
		alpha3: Alpha3CUB,
	}
	Curacao = Country{
		name:   NameCuracao,
		alpha2: Alpha2CW,
		alpha3: Alpha3CUW,
	}
	Cyprus = Country{
		name:   NameCyprus,
		alpha2: Alpha2CY,
		alpha3: Alpha3CYP,
	}
	Czechia = Country{
		name:   NameCzechia,
		alpha2: Alpha2CZ,
		alpha3: Alpha3CZE,
	}
	CoteDIvoire = Country{
		name:   NameCoteDIvoire,
		alpha2: Alpha2CI,
		alpha3: Alpha3CIV,
	}
	Denmark = Country{
		name:   NameDenmark,
		alpha2: Alpha2DK,
		alpha3: Alpha3DNK,
	}
	Djibouti = Country{
		name:   NameDjibouti,
		alpha2: Alpha2DJ,
		alpha3: Alpha3DJI,
	}
	Dominica = Country{
		name:   NameDominica,
		alpha2: Alpha2DM,
		alpha3: Alpha3DMA,
	}
	DominicanRepublic = Country{
		name:   NameDominicanRepublic,
		alpha2: Alpha2DO,
		alpha3: Alpha3DOM,
	}
	Ecuador = Country{
		name:   NameEcuador,
		alpha2: Alpha2EC,
		alpha3: Alpha3ECU,
	}
	Egypt = Country{
		name:   NameEgypt,
		alpha2: Alpha2EG,
		alpha3: Alpha3EGY,
	}
	ElSalvador = Country{
		name:   NameElSalvador,
		alpha2: Alpha2SV,
		alpha3: Alpha3SLV,
	}
	EquatorialGuinea = Country{
		name:   NameEquatorialGuinea,
		alpha2: Alpha2GQ,
		alpha3: Alpha3GNQ,
	}
	Eritrea = Country{
		name:   NameEritrea,
		alpha2: Alpha2ER,
		alpha3: Alpha3ERI,
	}
	Estonia = Country{
		name:   NameEstonia,
		alpha2: Alpha2EE,
		alpha3: Alpha3EST,
	}
	Eswatini = Country{
		name:   NameEswatini,
		alpha2: Alpha2SZ,
		alpha3: Alpha3SWZ,
	}
	Ethiopia = Country{
		name:   NameEthiopia,
		alpha2: Alpha2ET,
		alpha3: Alpha3ETH,
	}
	FalklandIslands = Country{
		name:   NameFalklandIslands,
		alpha2: Alpha2FK,
		alpha3: Alpha3FLK,
	}
	FaroeIslands = Country{
		name:   NameFaroeIslands,
		alpha2: Alpha2FO,
		alpha3: Alpha3FRO,
	}
	Fiji = Country{
		name:   NameFiji,
		alpha2: Alpha2FJ,
		alpha3: Alpha3FJI,
	}
	Finland = Country{
		name:   NameFinland,
		alpha2: Alpha2FI,
		alpha3: Alpha3FIN,
	}
	France = Country{
		name:   NameFrance,
		alpha2: Alpha2FR,
		alpha3: Alpha3FRA,
	}
	FrenchGuiana = Country{
		name:   NameFrenchGuiana,
		alpha2: Alpha2GF,
		alpha3: Alpha3GUF,
	}
	FrenchPolynesia = Country{
		name:   NameFrenchPolynesia,
		alpha2: Alpha2PF,
		alpha3: Alpha3PYF,
	}
	FrenchSouthernTerritories = Country{
		name:   NameFrenchSouthernTerritories,
		alpha2: Alpha2TF,
		alpha3: Alpha3ATF,
	}
	Gabon = Country{
		name:   NameGabon,
		alpha2: Alpha2GA,
		alpha3: Alpha3GAB,
	}
	Gambia = Country{
		name:   NameGambia,
		alpha2: Alpha2GM,
		alpha3: Alpha3GMB,
	}
	Georgia = Country{
		name:   NameGeorgia,
		alpha2: Alpha2GE,
		alpha3: Alpha3GEO,
	}
	Germany = Country{
		name:   NameGermany,
		alpha2: Alpha2DE,
		alpha3: Alpha3DEU,
	}
	Ghana = Country{
		name:   NameGhana,
		alpha2: Alpha2GH,
		alpha3: Alpha3GHA,
	}
	Gibraltar = Country{
		name:   NameGibraltar,
		alpha2: Alpha2GI,
		alpha3: Alpha3GIB,
	}
	Greece = Country{
		name:   NameGreece,
		alpha2: Alpha2GR,
		alpha3: Alpha3GRC,
	}
	Greenland = Country{
		name:   NameGreenland,
		alpha2: Alpha2GL,
		alpha3: Alpha3GRL,
	}
	Grenada = Country{
		name:   NameGrenada,
		alpha2: Alpha2GD,
		alpha3: Alpha3GRD,
	}
	Guadeloupe = Country{
		name:   NameGuadeloupe,
		alpha2: Alpha2GP,
		alpha3: Alpha3GLP,
	}
	Guam = Country{
		name:   NameGuam,
		alpha2: Alpha2GU,
		alpha3: Alpha3GUM,
	}
	Guatemala = Country{
		name:   NameGuatemala,
		alpha2: Alpha2GT,
		alpha3: Alpha3GTM,
	}
	Guernsey = Country{
		name:   NameGuernsey,
		alpha2: Alpha2GG,
		alpha3: Alpha3GGY,
	}
	Guinea = Country{
		name:   NameGuinea,
		alpha2: Alpha2GN,
		alpha3: Alpha3GIN,
	}
	GuineaBissau = Country{
		name:   NameGuineaBissau,
		alpha2: Alpha2GW,
		alpha3: Alpha3GNB,
	}
	Guyana = Country{
		name:   NameGuyana,
		alpha2: Alpha2GY,
		alpha3: Alpha3GUY,
	}
	Haiti = Country{
		name:   NameHaiti,
		alpha2: Alpha2HT,
		alpha3: Alpha3HTI,
	}
	HeardIslandAndMcDonaldIslands = Country{
		name:   NameHeardIslandAndMcDonaldIslands,
		alpha2: Alpha2HM,
		alpha3: Alpha3HMD,
	}
	HolySee = Country{
		name:   NameHolySee,
		alpha2: Alpha2VA,
		alpha3: Alpha3VAT,
	}
	Honduras = Country{
		name:   NameHonduras,
		alpha2: Alpha2HN,
		alpha3: Alpha3HND,
	}
	HongKong = Country{
		name:   NameHongKong,
		alpha2: Alpha2HK,
		alpha3: Alpha3HKG,
	}
	Hungary = Country{
		name:   NameHungary,
		alpha2: Alpha2HU,
		alpha3: Alpha3HUN,
	}
	Iceland = Country{
		name:   NameIceland,
		alpha2: Alpha2IS,
		alpha3: Alpha3ISL,
	}
	India = Country{
		name:   NameIndia,
		alpha2: Alpha2IN,
		alpha3: Alpha3IND,
	}
	Indonesia = Country{
		name:   NameIndonesia,
		alpha2: Alpha2ID,
		alpha3: Alpha3IDN,
	}
	Iran = Country{
		name:   NameIran,
		alpha2: Alpha2IR,
		alpha3: Alpha3IRN,
	}
	Iraq = Country{
		name:   NameIraq,
		alpha2: Alpha2IQ,
		alpha3: Alpha3IRQ,
	}
	Ireland = Country{
		name:   NameIreland,
		alpha2: Alpha2IE,
		alpha3: Alpha3IRL,
	}
	IsleOfMan = Country{
		name:   NameIsleOfMan,
		alpha2: Alpha2IM,
		alpha3: Alpha3IMN,
	}
	Israel = Country{
		name:   NameIsrael,
		alpha2: Alpha2IL,
		alpha3: Alpha3ISR,
	}
	Italy = Country{
		name:   NameItaly,
		alpha2: Alpha2IT,
		alpha3: Alpha3ITA,
	}
	Jamaica = Country{
		name:   NameJamaica,
		alpha2: Alpha2JM,
		alpha3: Alpha3JAM,
	}
	Japan = Country{
		name:   NameJapan,
		alpha2: Alpha2JP,
		alpha3: Alpha3JPN,
	}
	Jersey = Country{
		name:   NameJersey,
		alpha2: Alpha2JE,
		alpha3: Alpha3JEY,
	}
	Jordan = Country{
		name:   NameJordan,
		alpha2: Alpha2JO,
		alpha3: Alpha3JOR,
	}
	Kazakhstan = Country{
		name:   NameKazakhstan,
		alpha2: Alpha2KZ,
		alpha3: Alpha3KAZ,
	}
	Kenya = Country{
		name:   NameKenya,
		alpha2: Alpha2KE,
		alpha3: Alpha3KEN,
	}
	Kiribati = Country{
		name:   NameKiribati,
		alpha2: Alpha2KI,
		alpha3: Alpha3KIR,
	}
	NorthKorea = Country{
		name:   NameNorthKorea,
		alpha2: Alpha2KP,
		alpha3: Alpha3PRK,
	}
	SouthKorea = Country{
		name:   NameSouthKorea,
		alpha2: Alpha2KR,
		alpha3: Alpha3KOR,
	}
	Kuwait = Country{
		name:   NameKuwait,
		alpha2: Alpha2KW,
		alpha3: Alpha3KWT,
	}
	Kyrgyzstan = Country{
		name:   NameKyrgyzstan,
		alpha2: Alpha2KG,
		alpha3: Alpha3KGZ,
	}
	LaoPeoplesDemocraticRepublic = Country{
		name:   NameLaoPeoplesDemocraticRepublic,
		alpha2: Alpha2LA,
		alpha3: Alpha3LAO,
	}
	Latvia = Country{
		name:   NameLatvia,
		alpha2: Alpha2LV,
		alpha3: Alpha3LVA,
	}
	Lebanon = Country{
		name:   NameLebanon,
		alpha2: Alpha2LB,
		alpha3: Alpha3LBN,
	}
	Lesotho = Country{
		name:   NameLesotho,
		alpha2: Alpha2LS,
		alpha3: Alpha3LSO,
	}
	Liberia = Country{
		name:   NameLiberia,
		alpha2: Alpha2LR,
		alpha3: Alpha3LBR,
	}
	Libya = Country{
		name:   NameLibya,
		alpha2: Alpha2LY,
		alpha3: Alpha3LBY,
	}
	Liechtenstein = Country{
		name:   NameLiechtenstein,
		alpha2: Alpha2LI,
		alpha3: Alpha3LIE,
	}
	Lithuania = Country{
		name:   NameLithuania,
		alpha2: Alpha2LT,
		alpha3: Alpha3LTU,
	}
	Luxembourg = Country{
		name:   NameLuxembourg,
		alpha2: Alpha2LU,
		alpha3: Alpha3LUX,
	}
	Macao = Country{
		name:   NameMacao,
		alpha2: Alpha2MO,
		alpha3: Alpha3MAC,
	}
	Madagascar = Country{
		name:   NameMadagascar,
		alpha2: Alpha2MG,
		alpha3: Alpha3MDG,
	}
	Malawi = Country{
		name:   NameMalawi,
		alpha2: Alpha2MW,
		alpha3: Alpha3MWI,
	}
	Malaysia = Country{
		name:   NameMalaysia,
		alpha2: Alpha2MY,
		alpha3: Alpha3MYS,
	}
	Maldives = Country{
		name:   NameMaldives,
		alpha2: Alpha2MV,
		alpha3: Alpha3MDV,
	}
	Mali = Country{
		name:   NameMali,
		alpha2: Alpha2ML,
		alpha3: Alpha3MLI,
	}
	Malta = Country{
		name:   NameMalta,
		alpha2: Alpha2MT,
		alpha3: Alpha3MLT,
	}
	MarshallIslands = Country{
		name:   NameMarshallIslands,
		alpha2: Alpha2MH,
		alpha3: Alpha3MHL,
	}
	Martinique = Country{
		name:   NameMartinique,
		alpha2: Alpha2MQ,
		alpha3: Alpha3MTQ,
	}
	Mauritania = Country{
		name:   NameMauritania,
		alpha2: Alpha2MR,
		alpha3: Alpha3MRT,
	}
	Mauritius = Country{
		name:   NameMauritius,
		alpha2: Alpha2MU,
		alpha3: Alpha3MUS,
	}
	Mayotte = Country{
		name:   NameMayotte,
		alpha2: Alpha2YT,
		alpha3: Alpha3MYT,
	}
	Mexico = Country{
		name:   NameMexico,
		alpha2: Alpha2MX,
		alpha3: Alpha3MEX,
	}
	Micronesia = Country{
		name:   NameMicronesia,
		alpha2: Alpha2FM,
		alpha3: Alpha3FSM,
	}
	Moldova = Country{
		name:   NameMoldova,
		alpha2: Alpha2MD,
		alpha3: Alpha3MDA,
	}
	Monaco = Country{
		name:   NameMonaco,
		alpha2: Alpha2MC,
		alpha3: Alpha3MCO,
	}
	Mongolia = Country{
		name:   NameMongolia,
		alpha2: Alpha2MN,
		alpha3: Alpha3MNG,
	}
	Montenegro = Country{
		name:   NameMontenegro,
		alpha2: Alpha2ME,
		alpha3: Alpha3MNE,
	}
	Montserrat = Country{
		name:   NameMontserrat,
		alpha2: Alpha2MS,
		alpha3: Alpha3MSR,
	}
	Morocco = Country{
		name:   NameMorocco,
		alpha2: Alpha2MA,
		alpha3: Alpha3MAR,
	}
	Mozambique = Country{
		name:   NameMozambique,
		alpha2: Alpha2MZ,
		alpha3: Alpha3MOZ,
	}
	Myanmar = Country{
		name:   NameMyanmar,
		alpha2: Alpha2MM,
		alpha3: Alpha3MMR,
	}
	Namibia = Country{
		name:   NameNamibia,
		alpha2: Alpha2NA,
		alpha3: Alpha3NAM,
	}
	Nauru = Country{
		name:   NameNauru,
		alpha2: Alpha2NR,
		alpha3: Alpha3NRU,
	}
	Nepal = Country{
		name:   NameNepal,
		alpha2: Alpha2NP,
		alpha3: Alpha3NPL,
	}
	Netherlands = Country{
		name:   NameNetherlands,
		alpha2: Alpha2NL,
		alpha3: Alpha3NLD,
	}
	NewCaledonia = Country{
		name:   NameNewCaledonia,
		alpha2: Alpha2NC,
		alpha3: Alpha3NCL,
	}
	NewZealand = Country{
		name:   NameNewZealand,
		alpha2: Alpha2NZ,
		alpha3: Alpha3NZL,
	}
	Nicaragua = Country{
		name:   NameNicaragua,
		alpha2: Alpha2NI,
		alpha3: Alpha3NIC,
	}
	Niger = Country{
		name:   NameNiger,
		alpha2: Alpha2NE,
		alpha3: Alpha3NER,
	}
	Nigeria = Country{
		name:   NameNigeria,
		alpha2: Alpha2NG,
		alpha3: Alpha3NGA,
	}
	Niue = Country{
		name:   NameNiue,
		alpha2: Alpha2NU,
		alpha3: Alpha3NIU,
	}
	NorfolkIsland = Country{
		name:   NameNorfolkIsland,
		alpha2: Alpha2NF,
		alpha3: Alpha3NFK,
	}
	NorthMacedonia = Country{
		name:   NameNorthMacedonia,
		alpha2: Alpha2MK,
		alpha3: Alpha3MKD,
	}
	NorthernMarianaIslands = Country{
		name:   NameNorthernMarianaIslands,
		alpha2: Alpha2MP,
		alpha3: Alpha3MNP,
	}
	Norway = Country{
		name:   NameNorway,
		alpha2: Alpha2NO,
		alpha3: Alpha3NOR,
	}
	Oman = Country{
		name:   NameOman,
		alpha2: Alpha2OM,
		alpha3: Alpha3OMN,
	}
	Pakistan = Country{
		name:   NamePakistan,
		alpha2: Alpha2PK,
		alpha3: Alpha3PAK,
	}
	Palau = Country{
		name:   NamePalau,
		alpha2: Alpha2PW,
		alpha3: Alpha3PLW,
	}
	Palestine = Country{
		name:   NamePalestine,
		alpha2: Alpha2PS,
		alpha3: Alpha3PSE,
	}
	Panama = Country{
		name:   NamePanama,
		alpha2: Alpha2PA,
		alpha3: Alpha3PAN,
	}
	PapuaNewGuinea = Country{
		name:   NamePapuaNewGuinea,
		alpha2: Alpha2PG,
		alpha3: Alpha3PNG,
	}
	Paraguay = Country{
		name:   NameParaguay,
		alpha2: Alpha2PY,
		alpha3: Alpha3PRY,
	}
	Peru = Country{
		name:   NamePeru,
		alpha2: Alpha2PE,
		alpha3: Alpha3PER,
	}
	Philippines = Country{
		name:   NamePhilippines,
		alpha2: Alpha2PH,
		alpha3: Alpha3PHL,
	}
	Pitcairn = Country{
		name:   NamePitcairn,
		alpha2: Alpha2PN,
		alpha3: Alpha3PCN,
	}
	Poland = Country{
		name:   NamePoland,
		alpha2: Alpha2PL,
		alpha3: Alpha3POL,
	}
	Portugal = Country{
		name:   NamePortugal,
		alpha2: Alpha2PT,
		alpha3: Alpha3PRT,
	}
	PuertoRico = Country{
		name:   NamePuertoRico,
		alpha2: Alpha2PR,
		alpha3: Alpha3PRI,
	}
	Qatar = Country{
		name:   NameQatar,
		alpha2: Alpha2QA,
		alpha3: Alpha3QAT,
	}
	Romania = Country{
		name:   NameRomania,
		alpha2: Alpha2RO,
		alpha3: Alpha3ROU,
	}
	RussianFederation = Country{
		name:   NameRussianFederation,
		alpha2: Alpha2RU,
		alpha3: Alpha3RUS,
	}
	Rwanda = Country{
		name:   NameRwanda,
		alpha2: Alpha2RW,
		alpha3: Alpha3RWA,
	}
	Reunion = Country{
		name:   NameReunion,
		alpha2: Alpha2RE,
		alpha3: Alpha3REU,
	}
	SaintBarthelemy = Country{
		name:   NameSaintBarthelemy,
		alpha2: Alpha2BL,
		alpha3: Alpha3BLM,
	}
	SaintHelenaAscensionAndTristanDaCunha = Country{
		name:   NameSaintHelenaAscensionAndTristanDaCunha,
		alpha2: Alpha2SH,
		alpha3: Alpha3SHN,
	}
	SaintKittsAndNevis = Country{
		name:   NameSaintKittsAndNevis,
		alpha2: Alpha2KN,
		alpha3: Alpha3KNA,
	}
	SaintLucia = Country{
		name:   NameSaintLucia,
		alpha2: Alpha2LC,
		alpha3: Alpha3LCA,
	}
	SaintMartin = Country{
		name:   NameSaintMartin,
		alpha2: Alpha2MF,
		alpha3: Alpha3MAF,
	}
	SaintPierreAndMiquelon = Country{
		name:   NameSaintPierreAndMiquelon,
		alpha2: Alpha2PM,
		alpha3: Alpha3SPM,
	}
	SaintVincentAndTheGrenadines = Country{
		name:   NameSaintVincentAndTheGrenadines,
		alpha2: Alpha2VC,
		alpha3: Alpha3VCT,
	}
	Samoa = Country{
		name:   NameSamoa,
		alpha2: Alpha2WS,
		alpha3: Alpha3WSM,
	}
	SanMarino = Country{
		name:   NameSanMarino,
		alpha2: Alpha2SM,
		alpha3: Alpha3SMR,
	}
	SaoTomeAndPrincipe = Country{
		name:   NameSaoTomeAndPrincipe,
		alpha2: Alpha2ST,
		alpha3: Alpha3STP,
	}
	SaudiArabia = Country{
		name:   NameSaudiArabia,
		alpha2: Alpha2SA,
		alpha3: Alpha3SAU,
	}
	Senegal = Country{
		name:   NameSenegal,
		alpha2: Alpha2SN,
		alpha3: Alpha3SEN,
	}
	Serbia = Country{
		name:   NameSerbia,
		alpha2: Alpha2RS,
		alpha3: Alpha3SRB,
	}
	Seychelles = Country{
		name:   NameSeychelles,
		alpha2: Alpha2SC,
		alpha3: Alpha3SYC,
	}
	SierraLeone = Country{
		name:   NameSierraLeone,
		alpha2: Alpha2SL,
		alpha3: Alpha3SLE,
	}
	Singapore = Country{
		name:   NameSingapore,
		alpha2: Alpha2SG,
		alpha3: Alpha3SGP,
	}
	SintMaarten = Country{
		name:   NameSintMaarten,
		alpha2: Alpha2SX,
		alpha3: Alpha3SXM,
	}
	Slovakia = Country{
		name:   NameSlovakia,
		alpha2: Alpha2SK,
		alpha3: Alpha3SVK,
	}
	Slovenia = Country{
		name:   NameSlovenia,
		alpha2: Alpha2SI,
		alpha3: Alpha3SVN,
	}
	SolomonIslands = Country{
		name:   NameSolomonIslands,
		alpha2: Alpha2SB,
		alpha3: Alpha3SLB,
	}
	Somalia = Country{
		name:   NameSomalia,
		alpha2: Alpha2SO,
		alpha3: Alpha3SOM,
	}
	SouthAfrica = Country{
		name:   NameSouthAfrica,
		alpha2: Alpha2ZA,
		alpha3: Alpha3ZAF,
	}
	SouthGeorgiaAndTheSouthSandwichIslands = Country{
		name:   NameSouthGeorgiaAndTheSouthSandwichIslands,
		alpha2: Alpha2GS,
		alpha3: Alpha3SGS,
	}
	SouthSudan = Country{
		name:   NameSouthSudan,
		alpha2: Alpha2SS,
		alpha3: Alpha3SSD,
	}
	Spain = Country{
		name:   NameSpain,
		alpha2: Alpha2ES,
		alpha3: Alpha3ESP,
	}
	SriLanka = Country{
		name:   NameSriLanka,
		alpha2: Alpha2LK,
		alpha3: Alpha3LKA,
	}
	Sudan = Country{
		name:   NameSudan,
		alpha2: Alpha2SD,
		alpha3: Alpha3SDN,
	}
	Suriname = Country{
		name:   NameSuriname,
		alpha2: Alpha2SR,
		alpha3: Alpha3SUR,
	}
	SvalbardAndJanMayen = Country{
		name:   NameSvalbardAndJanMayen,
		alpha2: Alpha2SJ,
		alpha3: Alpha3SJM,
	}
	Sweden = Country{
		name:   NameSweden,
		alpha2: Alpha2SE,
		alpha3: Alpha3SWE,
	}
	Switzerland = Country{
		name:   NameSwitzerland,
		alpha2: Alpha2CH,
		alpha3: Alpha3CHE,
	}
	SyrianArabRepublic = Country{
		name:   NameSyrianArabRepublic,
		alpha2: Alpha2SY,
		alpha3: Alpha3SYR,
	}
	Taiwan = Country{
		name:   NameTaiwan,
		alpha2: Alpha2TW,
		alpha3: Alpha3TWN,
	}
	Tajikistan = Country{
		name:   NameTajikistan,
		alpha2: Alpha2TJ,
		alpha3: Alpha3TJK,
	}
	TanzaniaTheUnitedRepublicOf = Country{
		name:   NameTanzaniaTheUnitedRepublicOf,
		alpha2: Alpha2TZ,
		alpha3: Alpha3TZA,
	}
	Thailand = Country{
		name:   NameThailand,
		alpha2: Alpha2TH,
		alpha3: Alpha3THA,
	}
	TimorLeste = Country{
		name:   NameTimorLeste,
		alpha2: Alpha2TL,
		alpha3: Alpha3TLS,
	}
	Togo = Country{
		name:   NameTogo,
		alpha2: Alpha2TG,
		alpha3: Alpha3TGO,
	}
	Tokelau = Country{
		name:   NameTokelau,
		alpha2: Alpha2TK,
		alpha3: Alpha3TKL,
	}
	Tonga = Country{
		name:   NameTonga,
		alpha2: Alpha2TO,
		alpha3: Alpha3TON,
	}
	TrinidadAndTobago = Country{
		name:   NameTrinidadAndTobago,
		alpha2: Alpha2TT,
		alpha3: Alpha3TTO,
	}
	Tunisia = Country{
		name:   NameTunisia,
		alpha2: Alpha2TN,
		alpha3: Alpha3TUN,
	}
	Turkey = Country{
		name:   NameTurkey,
		alpha2: Alpha2TR,
		alpha3: Alpha3TUR,
	}
	Turkmenistan = Country{
		name:   NameTurkmenistan,
		alpha2: Alpha2TM,
		alpha3: Alpha3TKM,
	}
	TurksAndCaicosIslands = Country{
		name:   NameTurksAndCaicosIslands,
		alpha2: Alpha2TC,
		alpha3: Alpha3TCA,
	}
	Tuvalu = Country{
		name:   NameTuvalu,
		alpha2: Alpha2TV,
		alpha3: Alpha3TUV,
	}
	Uganda = Country{
		name:   NameUganda,
		alpha2: Alpha2UG,
		alpha3: Alpha3UGA,
	}
	Ukraine = Country{
		name:   NameUkraine,
		alpha2: Alpha2UA,
		alpha3: Alpha3UKR,
	}
	UnitedArabEmirates = Country{
		name:   NameUnitedArabEmirates,
		alpha2: Alpha2AE,
		alpha3: Alpha3ARE,
	}
	UnitedKingdomOfGreatBritainAndNorthernIreland = Country{
		name:   NameUnitedKingdomOfGreatBritainAndNorthernIreland,
		alpha2: Alpha2GB,
		alpha3: Alpha3GBR,
	}
	UnitedStatesMinorOutlyingIslands = Country{
		name:   NameUnitedStatesMinorOutlyingIslands,
		alpha2: Alpha2UM,
		alpha3: Alpha3UMI,
	}
	UnitedStatesOfAmerica = Country{
		name:   NameUnitedStatesOfAmerica,
		alpha2: Alpha2US,
		alpha3: Alpha3USA,
	}
	Uruguay = Country{
		name:   NameUruguay,
		alpha2: Alpha2UY,
		alpha3: Alpha3URY,
	}
	Uzbekistan = Country{
		name:   NameUzbekistan,
		alpha2: Alpha2UZ,
		alpha3: Alpha3UZB,
	}
	Vanuatu = Country{
		name:   NameVanuatu,
		alpha2: Alpha2VU,
		alpha3: Alpha3VUT,
	}
	Venezuela = Country{
		name:   NameVenezuela,
		alpha2: Alpha2VE,
		alpha3: Alpha3VEN,
	}
	VietNam = Country{
		name:   NameVietNam,
		alpha2: Alpha2VN,
		alpha3: Alpha3VNM,
	}
	BritishVirginIslands = Country{
		name:   NameBritishVirginIslands,
		alpha2: Alpha2VG,
		alpha3: Alpha3VGB,
	}
	USVirginIslands = Country{
		name:   NameUSVirginIslands,
		alpha2: Alpha2VI,
		alpha3: Alpha3VIR,
	}
	WallisAndFutuna = Country{
		name:   NameWallisAndFutuna,
		alpha2: Alpha2WF,
		alpha3: Alpha3WLF,
	}
	WesternSahara = Country{
		name:   NameWesternSahara,
		alpha2: Alpha2EH,
		alpha3: Alpha3ESH,
	}
	Yemen = Country{
		name:   NameYemen,
		alpha2: Alpha2YE,
		alpha3: Alpha3YEM,
	}
	Zambia = Country{
		name:   NameZambia,
		alpha2: Alpha2ZM,
		alpha3: Alpha3ZMB,
	}
	Zimbabwe = Country{
		name:   NameZimbabwe,
		alpha2: Alpha2ZW,
		alpha3: Alpha3ZWE,
	}
	AlandIslands = Country{
		name:   NameAlandIslands,
		alpha2: Alpha2AX,
		alpha3: Alpha3ALA,
	}
)
